# Generated by Django 4.0.4 on 2022-07-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userphoto',
            field=models.ImageField(null=True, upload_to='photos/% Y/% m/% d/'),
        ),
    ]
