# Generated by Django 4.0.4 on 2022-07-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_userphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isvarifaied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userphoto',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
