# Generated by Django 4.0.4 on 2022-07-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_isvarifaied_alter_userprofile_userphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
