# Generated by Django 4.0.4 on 2022-07-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpro', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proeritie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=254, verbose_name='date')),
                ('price', models.DecimalField(decimal_places=0, max_digits=30, null=True, verbose_name='price')),
                ('bedrooms', models.DecimalField(decimal_places=0, max_digits=2, null=True, verbose_name='bedrooms')),
                ('bathrooms', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='bathrooms')),
                ('sqft_living', models.DecimalField(decimal_places=0, max_digits=5, null=True, verbose_name='sqft living')),
                ('sqft_lot', models.DecimalField(decimal_places=0, max_digits=7, null=True, verbose_name='sqft lot')),
                ('floors', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='floors')),
                ('waterfront', models.DecimalField(decimal_places=0, max_digits=1, null=True, verbose_name='waterfront')),
                ('view', models.DecimalField(decimal_places=0, max_digits=1, null=True, verbose_name='view')),
                ('condition', models.DecimalField(decimal_places=0, max_digits=1, null=True, verbose_name='condition')),
                ('grade', models.DecimalField(decimal_places=0, max_digits=2, null=True, verbose_name='grade')),
                ('sqft_above', models.DecimalField(decimal_places=0, max_digits=4, null=True, verbose_name='sqft above')),
                ('sqft_basement', models.DecimalField(decimal_places=0, max_digits=4, null=True, verbose_name='sqft basement')),
                ('yr_built', models.TextField(max_length=4, null=True, verbose_name='yr built')),
                ('yr_renovated', models.TextField(max_length=4, null=True, verbose_name='yr built')),
                ('zipcode', models.DecimalField(decimal_places=0, max_digits=6, null=True, verbose_name='zipcode')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=20, null=True, verbose_name='lat')),
                ('long', models.DecimalField(decimal_places=7, max_digits=10, null=True, verbose_name='long')),
                ('sqft_living15', models.DecimalField(decimal_places=0, max_digits=4, null=True, verbose_name='sqft livingfif')),
                ('sqft_lot15', models.DecimalField(decimal_places=0, max_digits=7, null=True, verbose_name='sqft livingfif')),
                ('title', models.TextField(max_length=255, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
