# Generated by Django 4.0.4 on 2022-07-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listpro', '0004_proeritie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proeritie',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='proeritie',
            name='title',
        ),
    ]
