# Generated by Django 4.0.4 on 2022-07-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpro', '0005_remove_proeritie_photo_remove_proeritie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='proeritie',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='proeritie',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
