# Generated by Django 4.0.4 on 2022-08-04 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listpro', '0006_proeritie_photo_proeritie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='proeritie',
            name='rel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proeritie',
            name='date',
            field=models.DateField(null=True, verbose_name='date'),
        ),
    ]
