# Generated by Django 4.0.4 on 2022-08-04 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listpro', '0007_proeritie_rel_alter_proeritie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proeritie',
            name='rel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owne', to=settings.AUTH_USER_MODEL),
        ),
    ]
