# Generated by Django 4.0.4 on 2022-08-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpro', '0008_alter_proeritie_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proeritie',
            name='date',
            field=models.CharField(max_length=255, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='proeritie',
            name='lat',
            field=models.DecimalField(decimal_places=18, max_digits=20, null=True, verbose_name='lat'),
        ),
        migrations.AlterField(
            model_name='proeritie',
            name='long',
            field=models.DecimalField(decimal_places=18, max_digits=20, null=True, verbose_name='long'),
        ),
    ]
