# Generated by Django 4.0.4 on 2022-08-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpro', '0009_alter_proeritie_date_alter_proeritie_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proeritie',
            name='lat',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True, verbose_name='lat'),
        ),
        migrations.AlterField(
            model_name='proeritie',
            name='long',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True, verbose_name='long'),
        ),
    ]
