# Generated by Django 4.0.4 on 2022-08-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpro', '0010_alter_proeritie_lat_alter_proeritie_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='proeritie',
            name='type',
            field=models.CharField(choices=[('Rent', 're'), ('Sell', 'se')], max_length=50, null=True),
        ),
    ]
