# Generated by Django 4.0.4 on 2022-08-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpro', '0011_proeritie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proeritie',
            name='is_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proeritie',
            name='type',
            field=models.CharField(choices=[('Sell', 'se'), ('Rent', 're')], max_length=50, null=True),
        ),
    ]
